### ISSUE TITLE
Printing unprinted cards

### ISSUE THREAD

**Issue by trombonebiker** [ShowPanda/ShowBase#23]
How are we going to do this? I can easily write a method that will return all the unprinted cards, or something similar, but what would be the most useful thing for you to use?

**Comment by davidsmpsn** [comment]
Easiest way would probably be if you setup a page that when you clicked "print unprinted" it shows you a table of all unprinted cards. I can use this to create a long pdf with all the unprinted cards in it then.

**Comment by trombonebiker** [comment]
See comment in #4

**Comment by trombonebiker** [comment]
Would it be possible to put the pdf generation code in a method in models/card.rb ? Assuming there's a way to generate and save them in the background (see #4 ), that would allow a simple call to, say, @card.print that would allow recursive printing of all unprinted cards. See below.

`@cards.each do |card|
   if(card.printed == false)
      card.print
   end
end`

**Comment by trombonebiker** [comment]
I think that generating effectively the same pdf repeatedly is easier because it then means that any changes to layouts, etc. only have to be done in one place. It's also easier from the point of view of making database updates (for the :printed field in Card) in controllers/jobs is easier to find than in .html.erb for debugging/improvements. Also half the idea of doing this via ActiveJob and/or a printing server is that the user doesn't need to use the print dialog so they can just move on to their next task in the knowledge that the card will be printed for them, and so we don't have the problem of having to connect multiple computers to the same printer because it's all done via the server machine.

**Comment by davidsmpsn** [comment]
Not sure what you mean by the first bit but i suppose the last bit makes sense. I don't know how it all works though?

**Comment by trombonebiker** [comment]
Basically if you put a method in the model file (app/models/cards.rb) then you can call that method on any object of that class by writing 'object.method' in a controller or job. That means that you can write the code to generate and save a PDF completely separately to everything else, and I can easily use it to generate (and then print) the correct PDFs as and when needed. It also means that you can focus on the layout and I can focus on the correct execution of it.

Does that make more sense? All you need to do is write this sort of thing in app/models/card.rb

'def generate_pdf'
   '#code to generate and save a pdf in the background'
'end'

**Comment by davidsmpsn** [comment]
I'm going to try something other than prawn as I don't think it's possible to save in the background and it's also complicated to work out how to pass certain variables through.

**Comment by davidsmpsn** [comment]
How do I get the generate_pdf action to run when I press send for printing?

**Comment by davidsmpsn** [comment]
Doesn't matter, I've got it.

**Comment by davidsmpsn** [comment]
You'll need to install the Wicked PDF gem and also wkhtmltopdf:

[https://github.com/mileszs/wicked_pdf](https://github.com/mileszs/wicked_pdf)

**Comment by davidsmpsn** [comment]
How do I get the print unprinted button to access the print_unprinted method in the cards controller? Right now it seems to be trying to execute the show method?

**Comment by trombonebiker** [comment]
Is this fixed?

**Comment by davidsmpsn** [comment]
I'm still having trouble getting indexes sent to the print method. Maybe you could have a look at it.

**Comment by trombonebiker** [comment]
Any in particular?

**Comment by davidsmpsn** [comment]
The blank class sheets are probably the easiest as there's nothing else
happening there printing wise at the moment.

**Comment by trombonebiker** [comment]
You'll now have to put the template for the printable file in `app/pdf/reports/blank_class_sheet.pdf`
