### ISSUE TITLE
Can't seed database fully

### ISSUE THREAD

**Issue by davidsmpsn** [ShowPanda/ShowBase#31]
`rake db:seed` says there is an error with Mime type PDF?

**Comment by trombonebiker** [comment]
If you could copy the full output from running it in a comment, that would be useful.

**Comment by davidsmpsn** [comment]
`/Users/davidsimpson/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.5.1/lib/action_dispatch/http/mime_type.rb:163: warning: already initialized constant Mime::PDF`
`/Users/davidsimpson/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.5.1/lib/action_dispatch/http/mime_type.rb:163: warning: previous definition of PDF was here
rake aborted!`
`RangeError: 7506650524 is out of range for ActiveRecord::Type::Integer with limit 4`
`/Users/davidsimpson/ShowBase/db/seeds.rb:149:in '<top (required)>'`
`Tasks: TOP => db:seed`

**Comment by trombonebiker** [comment]
Try now?

**Comment by davidsmpsn** [comment]
This now shows up on `rake db:migrate`

`/Users/davidsimpson/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.5.1/lib/action_dispatch/http/mime_type.rb:163: warning: already initialized constant Mime::PDF`
`/Users/davidsimpson/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.5.1/lib/action_dispatch/http/mime_type.rb:163: warning: previous definition of PDF was here`

**Comment by trombonebiker** [comment]
I've had that for ages, everything will still work fine because it's just a warning.

**Comment by davidsmpsn** [comment]
I no longer have any entrants, trophies or cards in the database seed and I can't create entrants of trophies?

**Comment by trombonebiker** [comment]
What does your server say when you try to create them? It's working fine for me so I'm just trying to recreate what you're getting...

**Comment by trombonebiker** [comment]
If you want to see only the server output for a specific action:

1. Make sure your server is running and you're on the page you need to be on to execute the action you're testing.
2. Open up a new terminal in the root of the app.
3. Run `rake log:clear`
4. Execute the action you're testing.
5. Open up log/development.log in a text editor.

**Comment by davidsmpsn** [comment]
This is the result:
`NameError (uninitialized constant EntrantsController::Trophypoint):
  app/controllers/entrants_controller.rb:40:in `create'`

**Comment by trombonebiker** [comment]
Now?

**Comment by davidsmpsn** [comment]
`RangeError (7530807391 is out of range for ActiveRecord::Type::Integer with limit 4):
  app/controllers/entrants_controller.rb:42:in `create'`

**Comment by trombonebiker** [comment]
Are you doing this each time you try?

`rake db:drop`
`rake db:migrate`
`rake db:seed`

**Comment by davidsmpsn** [comment]
That worked. Thank you :)
