### ISSUE TITLE
Bad wkhtmltopdf path

### ISSUE THREAD

**Issue by trombonebiker** [ShowPanda/ShowBase#32]
Error in terminal is as follows, makes the print button for a card hang on the animation.

`RuntimeError (Bad wkhtmltopdf's path: bundler: command not found: which`
`Install missing gem executables with 'bundle install'):`
`app/models/card.rb:24:in 'new'`
`app/models/card.rb:24:in 'generate_pdf`
`app/jobs/print_cards_job.rb:6:in 'perform'`
`app/controllers/cards_controller.rb:68:in 'send_to_printer'`

I've installed all the gems in the gemfile, even added wkhtmltopdf specifically. The code that the errors point you towards are just places where the model object `WickedPdf` is used or a method containing it is used.

StackOverflow suggested I add the directory of the gem into the initialiser and add that same directory to my path variable, neither of which fixed it...

**Comment by davidsmpsn** [comment]
Did you do `rails generate wicked_pdf` after `bundle install`?

**Comment by trombonebiker** [comment]
Still not working

**Comment by trombonebiker** [comment]
Apparently `which` isn't a command in windows?

**Comment by trombonebiker** [comment]
Second comment

https://github.com/mileszs/wicked_pdf/issues/402

**Comment by davidsmpsn** [comment]
Does it work now?

**Comment by trombonebiker** [comment]
Same errors as before, I'll try installing the windows version of `which` and see if that does something

**Comment by trombonebiker** [comment]
Same again...

**Comment by trombonebiker** [comment]
`git push`?

**Comment by davidsmpsn** [comment]
You mean I should git push or you?

**Comment by trombonebiker** [comment]
If you've made changes, I can't use them unless you upload them

**Comment by davidsmpsn** [comment]
Not made any yet. You installed it like this yes? [http://wkhtmltopdf.org/downloads.html](http://wkhtmltopdf.org/downloads.html)

**Comment by trombonebiker** [comment]
Nope, from the gem. Will try that

**Comment by trombonebiker** [comment]
Can you check that it still works for you and close this issue if it does?
