### ISSUE TITLE
Card printing

### ISSUE THREAD

**Issue by trombonebiker** [ShowPanda/ShowBase#4]
- [x] Create pdf template for cards

- [x] Add "print this card" button in index and show views

- [x] Add "print all unprinted cards" button in index view

- [x] Add "print all cards for this entrant" button in entrant show view

- [x] Edit pdf template to fit the physical cards.

- [x] Set print button to silently print to the server machine's default printer, without opening the pdf in the current or a new tab.

**Comment by trombonebiker** [comment]
This article might help with the auto-printing.
http://stackoverflow.com/questions/6789880/how-can-i-put-a-print-link-button-on-my-project-page-to-printout-an-infomation

**Comment by davidsmpsn** [comment]
Going to try another pdf generator gem and see if it's any easier than Prawn

**Comment by trombonebiker** [comment]
I've had some problems trying to get these to print silently in the background. Web browsers (especially chrome) have a thing that won't let you silently print to the default printer without opening the print dialog first, to prevent large file prints being disguised as "Look at this cute cat!". I'm thinking that printing through Active Jobs might be the easiest way to do this; when you click a print button the relevant Active Job is set up and the server then processes the job when it's "idle", meaning that we can connect the printer to the server machine only and possibly not have to worry about creating PDFs on-screen.

Would the sort of algorithm below work?

# cards_controller.rb #

@cards.each do |card|
   *** setup print job (maybe via pdf) ***
end



# wherever the active job code is put #

def card_print_job
   *** generate a pdf for the card it's passed ***
   card.update(printed: true)
end

**Comment by trombonebiker** [comment]
Found this article, might be what we're looking for

http://dev.mikamai.com/post/82894788234/physically-printing-with-ruby

**Comment by trombonebiker** [comment]
This might also work, I'll try it this afternoon/evening sometime.

https://qz.io/wiki/2.0-Pixel-Printing#pdf-printing

**Comment by trombonebiker** [comment]
Managed to successfully load the QZ Tray sample html page and print their sample pdf and the current webpage to one of the university's cloud printing queues by setting it as the computer's default printer. Repeated and there was a delay of anywhere from 1 to 6 seconds each time, which for large numbers of cards could mean the server hangs while it processes all the cards to the print queue, so creating an ActiveJob is probably going to be necessary to allow users to carry on inputting data while the printing is handled and avoid server overloads.

**Comment by trombonebiker** [comment]
Tried adding the QZ Tray javascripts to the assets folder and some test buttons to the homescreen. Managed to detect the default printer but not print to it (yet).

**Comment by trombonebiker** [comment]
This seems to have turned into my sort of problem...

**Comment by trombonebiker** [comment]
Is there a way to easily generate a pdf in the background (i.e. without opening/displaying it) and save it somewhere like app/pdf/cards/ with filename "#{card.entrant_first_name}_#{card.entrant_surname}_#{card.section}_#{card.category}.pdf" ? If so, I think I can alter the QZ Tray javascript functions to allow us to print any pdf of our choice

**Comment by trombonebiker** [comment]
The printing problem has been solved with Foxit Reader version 6.2, which allows printing to the computer's default printer from the command line. The ruby `Kernel.system` method allows command line calls directly from ruby so once the default printer is set to the desired machine, then the ShowBase app does the rest in the background.

**Comment by trombonebiker** [comment]
@davidsmpsn can you print on your laptop yet? If so, it would be good to make the cards look like they have done in the past so we know that that part of the database is good to go.

**Comment by trombonebiker** [comment]
Do the generated card PDFs fit the actual cards we'll be printing on? Has it even been tried?

**Comment by davidsmpsn** [comment]
Yes the cards fit the paper used. I tried it a while ago.
