### ISSUE TITLE
Prize money printout

### ISSUE THREAD

**Issue by trombonebiker** [ShowPanda/ShowBase#42]
Need a printout of all the prize money per entrant for the treasurer to issue winnings with. It'll need a space for a signature for each entrant.

**Comment by davidsmpsn** [comment]
Have setup all the files but can't seem to work out how to get the entrants to pass to the pdf. See error on prize money reports page.

**Comment by trombonebiker** [comment]
You're carrying out `print_prize_money_job.rb` on an entrant object, while the pdf template `prize_money_pdf.html.erb` is expecting an array of entrant objects. Either change the pdf to accept only one entrant, or change the job to complete for an array of entrants.
